# docker-compose.yml
version: '3.8'

services:
  multi-agent-system:
    build: .
    container_name: multi-agent-system
    ports:
      - "8080:8080"   # API server
      - "11434:11434" # Ollama server
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./memory:/app/memory
      - ./scheduler:/app/scheduler
      - ollama-data:/root/.ollama
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=0.0.0.0:11434
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - LOG_LEVEL=INFO
      - MODEL_NAME=llama3.2:1b
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  ollama-data:
    driver: local

networks:
  default:
    name: multi-agent-network