# docker-compose.production.yml - Optimized for DigitalOcean Deployment
version: '3.8'

services:
  # Agentic AI Framework Application
  agentic-ai:
    build: .
    container_name: agentic-ai-production
    ports:
      - "8000:8000"
      - "80:8000"  # Also expose on port 80 for web access
    environment:
      - OLLAMA_URL=http://ollama:11434
      - DEFAULT_MODEL=deepseek-r1:1.5b
      - DATABASE_PATH=/app/data/agentic_ai.db
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - MAX_AGENT_ITERATIONS=3
      - SCHEDULER_INTERVAL=60
      - TOOLS_DIRECTORY=tools
    volumes:
      - ./data:/app/data
      - ./tools:/app/tools
      - ./logs:/app/logs
    depends_on:
      - ollama
      - model-downloader
    restart: unless-stopped
    networks:
      - agentic-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  # Ollama LLM Service
  ollama:
    image: ollama/ollama:latest
    container_name: agentic-ai-ollama-production
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=3
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - agentic-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '1.5'

  # Model Downloader - Downloads top 5 small models
  model-downloader:
    image: alpine/curl:latest
    container_name: agentic-ai-model-downloader
    depends_on:
      - ollama
    networks:
      - agentic-network
    command: >
      sh -c "
        echo 'Waiting for Ollama to be ready...' &&
        while ! curl -f http://ollama:11434/api/tags; do
          echo 'Ollama not ready, waiting 10 seconds...'
          sleep 10
        done &&
        
        echo '=== Starting model downloads ===' &&
        echo 'This will download 5 small models (total ~3.2GB)' &&
        
        # Model 1: TinyLlama 1.1B (~637MB) - Fast and efficient
        echo 'Downloading TinyLlama 1.1B (637MB)...' &&
        curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"tinyllama:1.1b\"}' -H 'Content-Type: application/json' &&
        echo '✓ TinyLlama downloaded' &&
        
        # Model 2: Granite 3.2 1B (~700MB) - IBM's efficient model
        echo 'Downloading Granite 3.2 1B (700MB)...' &&
        curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"granite3.2:2b\"}' -H 'Content-Type: application/json' &&
        echo '✓ Granite 3.2 downloaded' &&
        
        # Model 3: DeepSeek-Coder 1.3B (~776MB) - Code specialist
        echo 'Downloading DeepSeek-Coder 1.3B (776MB)...' &&
        curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"deepseek-coder:1.3b\"}' -H 'Content-Type: application/json' &&
        echo '✓ DeepSeek-Coder downloaded' &&
        
        # Model 4: DeepSeek-R1 1.5B (~1.1GB) - Reasoning specialist
        echo 'Downloading DeepSeek-R1 1.5B (1.1GB)...' &&
        curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"deepseek-r1:1.5b\"}' -H 'Content-Type: application/json' &&
        echo '✓ DeepSeek-R1 downloaded' &&
        
        echo '=== All models downloaded successfully! ===' &&
        echo 'Available models:' &&
        curl -s http://ollama:11434/api/tags | grep -o '\"name\":\"[^\"]*\"' &&
        echo 'Model downloader completed!'
      "
    restart: "no"

  # Optional: Simple web interface for testing
  web-interface:
    image: nginx:alpine
    container_name: agentic-ai-web
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
    depends_on:
      - agentic-ai
    restart: unless-stopped
    networks:
      - agentic-network

volumes:
  ollama_data:
    driver: local

networks:
  agentic-network:
    driver: bridge